# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ccccf5e15cba6ea934c40d22f5d92371c12c690c4964f0d4b018aba0407b48e55ff3dbf02bb0b45659cf4dc0787526f5d127e7a9cb773d9594b268634e71fda

test:
  secret_key_base: 60e402ae11cd855827ba89053eea5500c005f1cfdaed9524be8febcbbe128fb1ac90d5988a4d7658b5ede788a3a7dc0543338eb252ca9a67c23b34502d2b9140

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
